function prtyplt(filename)
% SUMMARY prtyplt

set(gcf, 'color', 'white');
set(gca, 'FontName', 'Helvetica');
set([hXLabel, hYLabel], ... % Caso sem Título
            'FontName', 'AvantGarde');
set([hXLabel, hYLabel, hLegend], 'FontSize', 12);
set(gca, ...
          'Box'         , 'off'     , ...
          'TickDir'     , 'out'     , ...
          'TickLength'  , [.02 .02] , ...
          'XMinorTick'  , 'on'      , ...
          'YMinorTick'  , 'on'      , ...
          'YGrid'       , 'on'      , ...
          'XColor'      , [.3 .3 .3], ...
          'YColor'      , [.3 .3 .3], ...
          'LineWidth'   , 1);
set(gcf, 'PaperPositionMode', 'auto');

print('-depsc2', '-r200', filename);
fixEPS(filename);
end